"""
config.py — pure-data constants for the EDC POC seeder.
No function definitions — only assignments.
"""

import os
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# DATABASE / PATHS
# ──────────────────────────────────────────────────────────────────────────────

DB_CONFIG = {
    "host":     os.getenv("PG_HOST",     "localhost"),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "dbname":   os.getenv("PG_DB",       "edtransmap"),
    "user":     os.getenv("PG_USER",     "postgres"),
    "password": os.getenv("PG_PASSWORD", "postgres"),
}

INPUT_DIR  = Path(__file__).parent / "input"
DATE_START = date(2026, 5, 1)
DATE_END   = date.today()         # inclusive

# ── Google Drive upload ───────────────────────────────────────────────────────
GDRIVE_FOLDER_ID   = ""           # paste your Drive folder ID here
GDRIVE_CREDENTIALS = Path(__file__).parent / "credentials.json"
GDRIVE_TOKEN       = Path(__file__).parent / "token.json"
GDRIVE_SCOPES      = ["https://www.googleapis.com/auth/drive.file"]

TERMINAL_MODELS = [
    "Verifone VX520",
    "Verifone V240m",
    "Ingenico iCT250",
    "Ingenico Move5000",
]

CARD_BRANDS   = ["VISA", "MASTERCARD", "JCB", "AMEX", "GPN"]
CARD_TYPES    = ["CREDIT", "DEBIT", "PREPAID"]
ISSUING_BANKS = [
    "Bank BCA", "Bank Mandiri", "Bank BNI", "Bank BRI",
    "Bank Permata", "CIMB Niaga", "Bank BTN", "Bank BSI",
]
CARD_PREFIXES = {
    "VISA":       ["4111", "4532", "4916", "4539"],
    "MASTERCARD": ["5400", "5105", "5500", "5425"],
    "JCB":        ["3530", "3566", "3500"],
    "AMEX":       ["3714", "3782", "3787"],
    "GPN":        ["6011", "6500", "6221"],
}

# ──────────────────────────────────────────────────────────────────────────────
# MCC MAPPING
# ──────────────────────────────────────────────────────────────────────────────

CATEGORY_TO_MCC = {
    # ── Original categories ──────────────────────────────────────────────────
    "Restaurant":                    "5812",
    "Casual Dining":                 "5812",
    "Fine Dining":                   "5812",
    "Coffee Shop":                   "5814",
    "Food-Beverage Specialty Store": "5499",
    "Clothing and Accessories":      "5651",
    "Women's Apparel":               "5621",
    "Children's Apparel":            "5641",
    "Florist":                       "5992",
    "Hair and Beauty":               "7230",
    "Wellness Center and Services":  "7298",
    "Therapist":                     "8049",
    "Dentist-Dental Office":         "8021",
    "School":                        "8220",
    "Language Studies":              "8220",
    "Training and Development":      "8249",
    "Bus Stop":                      "4111",
    "Convention-Exhibition Center":  "7990",
    # ── F&B ──────────────────────────────────────────────────────────────────
    "Bakery and Baked Goods Store":  "5462",
    "Butcher":                       "5499",
    "Convenience Store":             "5411",
    "Wine and Liquor":               "5921",
    "Bar or Pub":                    "5813",
    "Night Club":                    "5813",
    # ── Retail ───────────────────────────────────────────────────────────────
    "Specialty Store":               "5999",
    "Jeweler":                       "5944",
    "Sporting Goods Store":          "5941",
    "Major Appliance":               "5722",
    "Home Improvement-Hardware Store": "5251",
    "Floor and Carpet":              "5713",
    "Office Supply and Services Store": "5112",
    "Automobile Dealership-New Cars": "5511",
    "Pharmacy":                      "5912",
    # ── Services ─────────────────────────────────────────────────────────────
    "Car Wash-Detailing":            "7542",
    "Dry Cleaning and Laundry":      "7211",
    "Fitness-Health Club":           "7997",
    "Barber":                        "7241",
    "Pet Care":                      "5995",
    "Repair Service":                "7699",
    "Mobile Service Center":         "7629",
    "IT and Office Equipment Services": "7372",
    "Interior and Exterior Design":  "7389",
    "Business Service":              "7389",
    "Consumer Services":             "7299",
    "Couriers":                      "4215",
    "Tire Repair":                   "7534",
    "Billiards-Pool Hall":           "7993",
    "Video Arcade-Game Room":        "7993",
    "Golf Course":                   "7992",
    # ── Health ───────────────────────────────────────────────────────────────
    "Medical Services-Clinics":      "8099",
    "Hospital":                      "8062",
    # ── Real estate / other ──────────────────────────────────────────────────
    "Real Estate Services":          "6513",
    "Residential Area-Building":     "6512",
    # ── F&B (additional) ─────────────────────────────────────────────────────
    "Fast Food":                     "5814",
    "Deli":                          "5812",
    "Take Out and Delivery Only":    "5812",
    "Grocery":                       "5411",
    "Cigar and Tobacco Shop":        "5993",
    "Vaping Store":                  "5999",
    # ── Retail (additional) ──────────────────────────────────────────────────
    "Shoes-Footwear":                "5661",
    "Computer and Software":         "5734",
    "Mobile Retailer":               "5732",
    "Optical":                       "8043",
    # ── Services (additional) ────────────────────────────────────────────────
    "Hotel":                         "7011",
    "Karaoke":                       "5813",
    "Transportation Service":        "4789",
    "Wedding Services and Bridal Studio": "7230",
    # ── F&B additions ────────────────────────────────────────────────────────
    "Tea House":                     "5814",
    "Doughnut Shop":                 "5461",
    "Sweet Shop":                    "5441",
    "Cafeteria":                     "5812",
    "Food Market-Stall":             "5499",
    "Bistro":                        "5812",
    "Coffee-Tea":                    "5814",
    "Dairy Goods":                   "5451",
    "Specialty Food Store":          "5499",
    "Catering and Other Food Services": "5812",
    "B2B Restaurant Services":       "5812",
    "Food Production":               "5499",
    "Bar ot Pub":                    "5813",
    # ── Retail additions ─────────────────────────────────────────────────────
    "Furniture Store":               "5712",
    "Home Specialty Store":          "5712",
    "Consumer Electronics Store":    "5734",
    "Entertainment Electronics":     "5734",
    "Gift, Antique and Art":         "5947",
    "Pet Supply":                    "5995",
    "Toy Store":                     "5945",
    "Bookstore":                     "5942",
    "Arts and Crafts Supplies":      "5945",
    "Consumer Goods":                "5999",
    "Motorcycle Accessories":        "5571",
    "Men's Apparel":                 "5611",
    "Specialty Clothing Store":      "5699",
    "Speciality Store":              "5999",
    "General Merchandise":           "5399",
    "Flowers and Jewelry":           "5992",
    "Hunting-Fishing Shop":          "5941",
    "Hardware, House and Garden":    "5251",
    "Garden Center":                 "5261",
    "Record, CD and Video":          "5735",
    "Drugstore":                     "5912",
    "Drugstore or Pharmacy":         "5912",
    "Auto Parts":                    "5533",
    "Paint Store":                   "5198",
    "Power Equipment Dealer":        "5999",
    "Market":                        "5499",
    "Shopping Mall":                 "5999",
    "Glass and Window":              "5231",
    "Wholesale Store":               "5300",
    # ── Beauty additions ─────────────────────────────────────────────────────
    "Hair Salon":                    "7230",
    "Hair And Beauty":               "7230",
    "Nail Salon":                    "7230",
    "Body Piercing and Tattoos":     "7299",
    "Chiropractor":                  "8099",
    # ── Health additions ─────────────────────────────────────────────────────
    "Veterinarian":                  "0742",
    "Family-General Practice Physicians": "8099",
    "Hospital or Health Care Facility": "8062",
    "Healthcare and Healthcare Support Services": "8099",
    "COVID-19 Testing Site":         "8099",
    # ── Education additions ───────────────────────────────────────────────────
    "Primary School":                "8220",
    "Secondary School":              "8220",
    "Education Facility":            "8220",
    "Kindergarten and Childcare":    "8351",
    "Coaching Institute":            "8249",
    # ── Entertainment additions ───────────────────────────────────────────────
    "Cinema":                        "7832",
    "Nightlife-Entertainment":       "5813",
    "Live Entertainment-Music":      "7929",
    "Theatre, Music and Culture":    "7929",
    "Casino":                        "7995",
    "Leisure":                       "7991",
    "Entertainment and Recreation":  "7991",
    "Race Track":                    "7996",
    "Tourist Attraction":            "7991",
    "Aquarium":                      "7991",
    "Museum":                        "7991",
    "Fine Arts":                     "5999",
    "Adult Entertainment":           "7273",
    "Video and Game Rental":         "7841",
    # ── Sports / events additions ─────────────────────────────────────────────
    "Event Spaces":                  "7990",
    "Sports Complex-Stadium":        "7941",
    "Sports Facility-Venue":         "7997",
    "Sports Field":                  "7997",
    "Golf Practice Range":           "7992",
    "Swimming Pool":                 "7997",
    "Basketball":                    "7997",
    "Sporting Instruction and Camps":"7941",
    "Outdoor-Recreation":            "7999",
    "Park-Recreation Area":          "7996",
    "Running Track":                 "7997",
    # ── Hospitality additions ────────────────────────────────────────────────
    "Guest House":                   "7011",
    "Hotel or Motel":                "7011",
    "Lodging":                       "7011",
    "Bed and Breakfast":             "7011",
    "Hostel":                        "7011",
    "Clubhouse":                     "7997",
    "Apartment Rental-Flat Rental":  "6513",
    # ── Automotive additions ──────────────────────────────────────────────────
    "Car Repair-Service":            "7531",
    "Car Repair":                    "7531",
    "Motorcycle Dealership":         "5571",
    "Motorcycle Service and Maintenance": "7699",
    "Truck Repair":                  "7513",
    "Bicycle and Bicycle Accessories Shop": "5941",
    "Bicycle Service and Maintenance": "7699",
    "Rental Car Agency":             "7512",
    "EV Charging Station":           "5552",
    "Petrol-Gasoline Station":       "5541",
    # ── Financial services additions ─────────────────────────────────────────
    "Bank":                          "6012",
    "Post Office":                   "9402",
    "Money Transferring Service":    "6099",
    "Finance and Insurance":         "6411",
    "Financial Investment Firm":     "6211",
    "Pawnshop":                      "5933",
    "Tax Service":                   "7276",
    "Legal Services":                "8111",
    "Attorney":                      "8111",
    "Property Management":           "6513",
    # ── Professional services additions ──────────────────────────────────────
    "Management and Consulting Services": "7389",
    "Business Facility":             "7389",
    "Advertising-Marketing, PR and Market Research": "7311",
    "Human Resources and Recruiting Services": "7361",
    "Engineering and Scientific Services": "8711",
    "Printing and Publishing":       "2791",
    "Modeling Agencies":             "7389",
    "B2B Sales and Services":        "7389",
    # ── Consumer services additions ───────────────────────────────────────────
    "Customer Care-Service Center":  "7299",
    "Travel Agent-Ticketing":        "4722",
    "Photography":                   "7221",
    "Tailor and Alteration":         "5699",
    "Internet Cafe":                 "7375",
    "Locksmiths and Security Systems Services": "7382",
    "Cargo Transportation":          "4215",
    "Fulfillment and Distribution Center": "4215",
    "Storage":                       "4225",
    "Mover":                         "4214",
    "Rental and Leasing":            "7394",
    "Repair and Maintenance Services": "7699",
    "Landscaping Services":          "0780",
    "Electrical":                    "1731",
    "Specialty Trade Contractors":   "1711",
    "Commercial Services":           "7389",
    "Cargo Center":                  "4215",
    "Outdoor Service":               "0780",
    "Manufacturing":                 "5065",
    "Warehouse":                     "4225",
    # ── Religion / community additions ───────────────────────────────────────
    "Mosque":                        "8661",
    "Temple":                        "8661",
    "Church":                        "8661",
    "Religious Place":               "8661",
    "Social Service":                "8398",
    "Organizations and Societies":   "8699",
    "Civic-Community Center":        "7997",
    "Government Office":             "9399",
    "Government or Community Facility": "9399",
    "Collective Community":          "8699",
}

# ──────────────────────────────────────────────────────────────────────────────
# CATEGORY PROFILES  (transactions/day range, IDR amount range)
# ──────────────────────────────────────────────────────────────────────────────

VOLUME_PROFILE = {
    "Restaurant":                    (30, 150),
    "Casual Dining":                 (30, 150),
    "Fine Dining":                   (15,  60),
    "Coffee Shop":                   (30, 150),
    "Food-Beverage Specialty Store": (20,  80),
    "Bakery and Baked Goods Store":  (20,  80),
    "Butcher":                       (10,  40),
    "Convenience Store":             (30, 120),
    "Wine and Liquor":               ( 5,  25),
    "Bar or Pub":                    (15,  60),
    "Night Club":                    (10,  50),
    "Clothing and Accessories":      (10,  50),
    "Women's Apparel":               (10,  50),
    "Children's Apparel":            ( 5,  25),
    "Specialty Store":               ( 5,  25),
    "Jeweler":                       ( 2,  15),
    "Sporting Goods Store":          ( 5,  20),
    "Pharmacy":                      (10,  40),
    "Florist":                       ( 5,  30),
    "Hair and Beauty":               ( 5,  25),
    "Barber":                        ( 8,  30),
    "Wellness Center and Services":  ( 3,  20),
    "Therapist":                     ( 3,  20),
    "Fitness-Health Club":           ( 5,  25),
    "Pet Care":                      ( 3,  15),
    "Dentist-Dental Office":         ( 3,  15),
    "Medical Services-Clinics":      ( 5,  25),
    "Hospital":                      ( 5,  20),
    "School":                        ( 1,   8),
    "Language Studies":              ( 2,  10),
    "Training and Development":      ( 2,  10),
    "Convention-Exhibition Center":  ( 1,   8),
    "Car Wash-Detailing":            ( 5,  20),
    "Dry Cleaning and Laundry":      ( 5,  20),
    "Repair Service":                ( 3,  15),
    "Mobile Service Center":         ( 5,  20),
    "Fast Food":                     (30, 120),
    "Deli":                          (15,  60),
    "Take Out and Delivery Only":    (15,  60),
    "Grocery":                       (20,  80),
    "Cigar and Tobacco Shop":        ( 3,  15),
    "Vaping Store":                  ( 3,  15),
    "Shoes-Footwear":                ( 5,  25),
    "Computer and Software":         ( 2,  10),
    "Mobile Retailer":               ( 3,  15),
    "Optical":                       ( 2,  10),
    "Hotel":                         ( 5,  20),
    "Karaoke":                       ( 5,  25),
    "Transportation Service":        ( 3,  15),
    "Wedding Services and Bridal Studio": ( 1,   5),
    # ── F&B additions ────────────────────────────────────────────────────────
    "Tea House":                     (15,  60),
    "Doughnut Shop":                 (20,  80),
    "Cafeteria":                     (20,  80),
    "Food Market-Stall":             (30, 100),
    "Sweet Shop":                    (15,  60),
    "Bistro":                        (20,  80),
    "Coffee-Tea":                    (25,  80),
    "Dairy Goods":                   (10,  40),
    "Specialty Food Store":          (10,  40),
    "Catering and Other Food Services": ( 3,  15),
    "B2B Restaurant Services":       ( 2,  10),
    "Food Production":               ( 2,  10),
    "Bar ot Pub":                    (15,  60),
    # ── Retail additions ─────────────────────────────────────────────────────
    "Furniture Store":               ( 2,  10),
    "Home Specialty Store":          ( 3,  15),
    "Consumer Electronics Store":    ( 5,  20),
    "Gift, Antique and Art":         ( 3,  15),
    "Pet Supply":                    ( 5,  20),
    "Toy Store":                     ( 5,  20),
    "Bookstore":                     ( 5,  20),
    "Arts and Crafts Supplies":      ( 5,  20),
    "Entertainment Electronics":     ( 3,  15),
    "Consumer Goods":                (10,  40),
    "Motorcycle Accessories":        ( 5,  20),
    "Glass and Window":              ( 2,  10),
    "Men's Apparel":                 (10,  50),
    "Wholesale Store":               ( 5,  25),
    "Specialty Clothing Store":      ( 8,  40),
    "Speciality Store":              ( 5,  25),
    "General Merchandise":           (10,  40),
    "Flowers and Jewelry":           ( 5,  25),
    "Hunting-Fishing Shop":          ( 3,  15),
    "Hardware, House and Garden":    ( 5,  20),
    "Garden Center":                 ( 5,  20),
    "Record, CD and Video":          ( 3,  15),
    "Drugstore":                     (10,  40),
    "Drugstore or Pharmacy":         (10,  40),
    "Auto Parts":                    ( 5,  20),
    "Paint Store":                   ( 5,  20),
    "Power Equipment Dealer":        ( 2,  10),
    "Market":                        (20,  80),
    "Shopping Mall":                 (10,  40),
    "Office Supply and Services Store": ( 5,  20),
    # ── Beauty additions ─────────────────────────────────────────────────────
    "Hair Salon":                    ( 5,  25),
    "Hair And Beauty":               ( 5,  25),
    "Nail Salon":                    ( 8,  30),
    "Body Piercing and Tattoos":     ( 2,  10),
    "Chiropractor":                  ( 3,  15),
    # ── Health additions ─────────────────────────────────────────────────────
    "Veterinarian":                  ( 3,  15),
    "Family-General Practice Physicians": ( 5,  25),
    "Hospital or Health Care Facility": ( 5,  20),
    "Healthcare and Healthcare Support Services": ( 3,  15),
    "COVID-19 Testing Site":         ( 5,  30),
    # ── Education additions ───────────────────────────────────────────────────
    "Primary School":                ( 1,   8),
    "Secondary School":              ( 1,   8),
    "Education Facility":            ( 1,   8),
    "Kindergarten and Childcare":    ( 1,   5),
    "Coaching Institute":            ( 2,  10),
    # ── Entertainment additions ───────────────────────────────────────────────
    "Cinema":                        (10,  50),
    "Nightlife-Entertainment":       ( 5,  30),
    "Live Entertainment-Music":      ( 5,  30),
    "Theatre, Music and Culture":    ( 5,  25),
    "Casino":                        ( 3,  20),
    "Leisure":                       ( 5,  25),
    "Entertainment and Recreation":  ( 5,  25),
    "Race Track":                    ( 2,  15),
    "Tourist Attraction":            ( 5,  30),
    "Aquarium":                      ( 3,  20),
    "Museum":                        ( 3,  20),
    "Sporting Instruction and Camps":( 3,  15),
    "Fine Arts":                     ( 2,  10),
    "Adult Entertainment":           ( 5,  25),
    "Video and Game Rental":         ( 3,  15),
    # ── Events / sports additions ─────────────────────────────────────────────
    "Event Spaces":                  ( 2,  15),
    "Sports Complex-Stadium":        ( 3,  20),
    "Sports Facility-Venue":         ( 3,  20),
    "Sports Field":                  ( 3,  15),
    "Golf Practice Range":           ( 2,  10),
    "Swimming Pool":                 ( 5,  25),
    "Basketball":                    ( 5,  25),
    "Running Track":                 ( 3,  15),
    "Outdoor-Recreation":            ( 3,  15),
    "Park-Recreation Area":          ( 3,  15),
    "Garden":                        ( 2,  10),
    # ── Hospitality additions ────────────────────────────────────────────────
    "Guest House":                   ( 3,  15),
    "Hotel or Motel":                ( 5,  20),
    "Lodging":                       ( 3,  15),
    "Bed and Breakfast":             ( 2,  10),
    "Hostel":                        ( 3,  15),
    "Clubhouse":                     ( 2,  10),
    "Apartment Rental-Flat Rental":  ( 1,   5),
    # ── Automotive additions ──────────────────────────────────────────────────
    "Car Repair-Service":            ( 3,  15),
    "Car Repair":                    ( 3,  15),
    "Motorcycle Dealership":         ( 1,   5),
    "Motorcycle Service and Maintenance": ( 3,  15),
    "Truck Repair":                  ( 2,  10),
    "Bicycle and Bicycle Accessories Shop": ( 3,  15),
    "Bicycle Service and Maintenance": ( 3,  15),
    "Rental Car Agency":             ( 3,  15),
    "EV Charging Station":           (10,  40),
    "Petrol-Gasoline Station":       (20,  80),
    # ── Services additions ────────────────────────────────────────────────────
    "Bank":                          ( 5,  25),
    "Post Office":                   ( 5,  20),
    "Money Transferring Service":    ( 5,  25),
    "Finance and Insurance":         ( 2,  10),
    "Financial Investment Firm":     ( 1,   8),
    "Pawnshop":                      ( 3,  15),
    "Legal Services":                ( 1,   5),
    "Attorney":                      ( 1,   5),
    "Tax Service":                   ( 2,  10),
    "Property Management":           ( 1,   5),
    "Management and Consulting Services": ( 1,   5),
    "Business Facility":             ( 2,  10),
    "Advertising-Marketing, PR and Market Research": ( 1,   5),
    "Human Resources and Recruiting Services": ( 1,   5),
    "Customer Care-Service Center":  ( 3,  15),
    "Travel Agent-Ticketing":        ( 3,  15),
    "Telephone Service":             ( 3,  15),
    "Photography":                   ( 2,  10),
    "Printing and Publishing":       ( 2,  10),
    "Electrical":                    ( 2,  10),
    "Landscaping Services":          ( 1,   8),
    "Storage":                       ( 1,   5),
    "Mover":                         ( 1,   5),
    "Cargo Center":                  ( 2,  10),
    "Commercial Services":           ( 2,  10),
    "Rental and Leasing":            ( 2,  10),
    "Repair and Maintenance Services": ( 3,  15),
    "Tailor and Alteration":         ( 3,  15),
    "Internet Cafe":                 ( 5,  25),
    "Locksmiths and Security Systems Services": ( 1,   8),
    "Couriers":                      ( 5,  25),
    "Cargo Transportation":          ( 2,  10),
    "Engineering and Scientific Services": ( 1,   5),
    "Modeling Agencies":             ( 1,   5),
    "B2B Sales and Services":        ( 2,  10),
    "Specialty Trade Contractors":   ( 1,   5),
    "Fulfillment and Distribution Center": ( 2,  10),
    "Outdoor Service":               ( 2,  10),
    "Manufacturing":                 ( 1,   5),
    "Real Estate Services":          ( 1,   5),
    "Residential Area-Building":     ( 1,   5),
    "Warehouse":                     ( 1,   5),
    "Facilities":                    ( 1,   5),
    # ── Religion / community additions ───────────────────────────────────────
    "Mosque":                        ( 2,  10),
    "Temple":                        ( 2,  10),
    "Church":                        ( 2,  10),
    "Religious Place":               ( 2,  10),
    "Social Service":                ( 1,   5),
    "Organizations and Societies":   ( 1,   5),
    "Civic-Community Center":        ( 2,  10),
    "Government Office":             ( 2,  10),
    "Government or Community Facility": ( 2,  10),
    "Collective Community":          ( 1,   5),
}

AMOUNT_RANGE = {
    "Restaurant":                    (  25_000,   500_000),
    "Casual Dining":                 (  25_000,   500_000),
    "Fine Dining":                   ( 100_000, 1_500_000),
    "Coffee Shop":                   (  20_000,   150_000),
    "Food-Beverage Specialty Store": (  20_000,   150_000),
    "Bakery and Baked Goods Store":  (  15_000,   100_000),
    "Butcher":                       (  30_000,   300_000),
    "Convenience Store":             (  10_000,   200_000),
    "Wine and Liquor":               (  50_000,   500_000),
    "Bar or Pub":                    (  30_000,   400_000),
    "Night Club":                    (  50_000,   500_000),
    "Clothing and Accessories":      (  50_000, 2_000_000),
    "Women's Apparel":               (  50_000, 2_000_000),
    "Children's Apparel":            (  50_000,   500_000),
    "Specialty Store":               (  50_000, 1_000_000),
    "Jeweler":                       ( 200_000, 5_000_000),
    "Sporting Goods Store":          (  50_000, 1_500_000),
    "Pharmacy":                      (  20_000,   500_000),
    "Florist":                       (  50_000,   500_000),
    "Hair and Beauty":               ( 100_000, 1_000_000),
    "Barber":                        (  30_000,   150_000),
    "Wellness Center and Services":  ( 100_000, 1_500_000),
    "Therapist":                     ( 100_000, 1_000_000),
    "Fitness-Health Club":           ( 100_000, 1_000_000),
    "Pet Care":                      (  50_000,   500_000),
    "Dentist-Dental Office":         ( 200_000, 2_000_000),
    "Medical Services-Clinics":      (  50_000,   500_000),
    "Hospital":                      ( 100_000, 2_000_000),
    "School":                        (  50_000,   500_000),
    "Language Studies":              (  50_000,   500_000),
    "Training and Development":      ( 100_000, 2_000_000),
    "Convention-Exhibition Center":  ( 100_000, 2_000_000),
    "Car Wash-Detailing":            (  30_000,   300_000),
    "Dry Cleaning and Laundry":      (  20_000,   200_000),
    "Repair Service":                (  30_000,   500_000),
    "Mobile Service Center":         (  30_000,   500_000),
    "Automobile Dealership-New Cars":( 500_000, 5_000_000),
    "Fast Food":                     (  15_000,   100_000),
    "Deli":                          (  20_000,   200_000),
    "Take Out and Delivery Only":    (  20_000,   200_000),
    "Grocery":                       (  50_000,   500_000),
    "Cigar and Tobacco Shop":        (  20_000,   200_000),
    "Vaping Store":                  (  50_000,   500_000),
    "Shoes-Footwear":                (  50_000, 1_500_000),
    "Computer and Software":         ( 100_000, 5_000_000),
    "Mobile Retailer":               (  50_000, 2_000_000),
    "Optical":                       ( 200_000, 2_000_000),
    "Hotel":                         ( 300_000, 3_000_000),
    "Karaoke":                       (  50_000,   500_000),
    "Transportation Service":        (  20_000,   200_000),
    "Wedding Services and Bridal Studio": ( 500_000, 10_000_000),
    # ── F&B additions ────────────────────────────────────────────────────────
    "Tea House":                     (  20_000,   150_000),
    "Doughnut Shop":                 (  15_000,    80_000),
    "Cafeteria":                     (  10_000,   100_000),
    "Food Market-Stall":             (   5_000,    50_000),
    "Sweet Shop":                    (  10_000,    80_000),
    "Bistro":                        (  25_000,   300_000),
    "Coffee-Tea":                    (  20_000,   150_000),
    "Dairy Goods":                   (  15_000,   100_000),
    "Specialty Food Store":          (  20_000,   200_000),
    "Catering and Other Food Services": ( 100_000, 2_000_000),
    "B2B Restaurant Services":       ( 100_000, 1_000_000),
    "Food Production":               (  50_000,   500_000),
    "Bar ot Pub":                    (  30_000,   400_000),
    # ── Retail additions ─────────────────────────────────────────────────────
    "Furniture Store":               ( 200_000, 5_000_000),
    "Home Specialty Store":          (  50_000, 2_000_000),
    "Consumer Electronics Store":    ( 200_000, 8_000_000),
    "Gift, Antique and Art":         (  50_000, 1_000_000),
    "Pet Supply":                    (  30_000,   500_000),
    "Toy Store":                     (  30_000,   500_000),
    "Bookstore":                     (  20_000,   300_000),
    "Arts and Crafts Supplies":      (  20_000,   300_000),
    "Entertainment Electronics":     ( 100_000, 5_000_000),
    "Consumer Goods":                (  20_000,   300_000),
    "Motorcycle Accessories":        (  50_000, 1_000_000),
    "Glass and Window":              (  50_000, 1_000_000),
    "Men's Apparel":                 (  50_000, 2_000_000),
    "Wholesale Store":               ( 100_000, 5_000_000),
    "Specialty Clothing Store":      (  50_000, 2_000_000),
    "Speciality Store":              (  50_000, 1_000_000),
    "General Merchandise":           (  20_000,   500_000),
    "Flowers and Jewelry":           (  50_000,   500_000),
    "Hunting-Fishing Shop":          (  50_000,   500_000),
    "Hardware, House and Garden":    (  30_000,   500_000),
    "Garden Center":                 (  30_000,   500_000),
    "Record, CD and Video":          (  20_000,   300_000),
    "Drugstore":                     (  20_000,   500_000),
    "Drugstore or Pharmacy":         (  20_000,   500_000),
    "Auto Parts":                    (  30_000, 1_000_000),
    "Paint Store":                   (  20_000,   500_000),
    "Power Equipment Dealer":        ( 200_000, 5_000_000),
    "Market":                        (  10_000,   200_000),
    "Shopping Mall":                 (  50_000, 1_000_000),
    "Office Supply and Services Store": ( 20_000,   300_000),
    # ── Beauty additions ─────────────────────────────────────────────────────
    "Hair Salon":                    ( 100_000, 1_000_000),
    "Hair And Beauty":               ( 100_000, 1_000_000),
    "Nail Salon":                    (  50_000,   300_000),
    "Body Piercing and Tattoos":     (  50_000,   500_000),
    "Chiropractor":                  ( 100_000,   800_000),
    # ── Health additions ─────────────────────────────────────────────────────
    "Veterinarian":                  (  50_000,   500_000),
    "Family-General Practice Physicians": ( 50_000,   500_000),
    "Hospital or Health Care Facility": ( 100_000, 3_000_000),
    "Healthcare and Healthcare Support Services": ( 50_000,   500_000),
    "COVID-19 Testing Site":         (  50_000,   300_000),
    # ── Education additions ───────────────────────────────────────────────────
    "Primary School":                (  50_000,   500_000),
    "Secondary School":              (  50_000,   500_000),
    "Education Facility":            (  50_000,   500_000),
    "Kindergarten and Childcare":    ( 100_000,   800_000),
    "Coaching Institute":            (  50_000,   500_000),
    # ── Entertainment additions ───────────────────────────────────────────────
    "Cinema":                        (  30_000,   200_000),
    "Nightlife-Entertainment":       (  50_000,   500_000),
    "Live Entertainment-Music":      (  50_000, 1_000_000),
    "Theatre, Music and Culture":    (  50_000,   500_000),
    "Casino":                        ( 100_000, 5_000_000),
    "Leisure":                       (  20_000,   300_000),
    "Entertainment and Recreation":  (  20_000,   300_000),
    "Race Track":                    (  50_000,   500_000),
    "Tourist Attraction":            (  20_000,   300_000),
    "Aquarium":                      (  30_000,   200_000),
    "Museum":                        (  20_000,   150_000),
    "Sporting Instruction and Camps":( 100_000, 1_000_000),
    "Fine Arts":                     (  50_000, 2_000_000),
    "Adult Entertainment":           (  50_000,   500_000),
    "Video and Game Rental":         (  10_000,   100_000),
    # ── Events / sports additions ─────────────────────────────────────────────
    "Event Spaces":                  ( 200_000, 5_000_000),
    "Sports Complex-Stadium":        (  30_000,   500_000),
    "Sports Facility-Venue":         (  30_000,   500_000),
    "Sports Field":                  (  20_000,   200_000),
    "Golf Practice Range":           (  50_000,   500_000),
    "Swimming Pool":                 (  20_000,   200_000),
    "Basketball":                    (  20_000,   200_000),
    "Running Track":                 (  10_000,   100_000),
    "Outdoor-Recreation":            (  20_000,   300_000),
    "Park-Recreation Area":          (  10_000,   100_000),
    "Garden":                        (  10_000,   100_000),
    # ── Hospitality additions ────────────────────────────────────────────────
    "Guest House":                   ( 100_000,   500_000),
    "Hotel or Motel":                ( 200_000, 2_000_000),
    "Lodging":                       ( 100_000, 1_000_000),
    "Bed and Breakfast":             ( 150_000,   800_000),
    "Hostel":                        (  50_000,   300_000),
    "Clubhouse":                     (  50_000,   500_000),
    "Apartment Rental-Flat Rental":  ( 500_000, 5_000_000),
    # ── Automotive additions ──────────────────────────────────────────────────
    "Car Repair-Service":            (  50_000, 1_500_000),
    "Car Repair":                    (  50_000, 1_500_000),
    "Motorcycle Dealership":         ( 500_000, 8_000_000),
    "Motorcycle Service and Maintenance": ( 30_000,   500_000),
    "Truck Repair":                  ( 100_000, 3_000_000),
    "Bicycle and Bicycle Accessories Shop": ( 50_000,   500_000),
    "Bicycle Service and Maintenance": ( 20_000,   200_000),
    "Rental Car Agency":             ( 200_000, 2_000_000),
    "EV Charging Station":           (  30_000,   200_000),
    "Petrol-Gasoline Station":       (  50_000,   500_000),
    # ── Services additions ────────────────────────────────────────────────────
    "Bank":                          (  50_000,   500_000),
    "Post Office":                   (  10_000,   200_000),
    "Money Transferring Service":    (  50_000, 2_000_000),
    "Finance and Insurance":         ( 100_000, 5_000_000),
    "Financial Investment Firm":     ( 200_000, 5_000_000),
    "Pawnshop":                      (  50_000, 2_000_000),
    "Legal Services":                ( 200_000, 5_000_000),
    "Attorney":                      ( 200_000, 5_000_000),
    "Tax Service":                   ( 100_000, 2_000_000),
    "Property Management":           ( 200_000, 5_000_000),
    "Management and Consulting Services": ( 200_000, 5_000_000),
    "Business Facility":             ( 100_000, 2_000_000),
    "Advertising-Marketing, PR and Market Research": ( 200_000, 5_000_000),
    "Human Resources and Recruiting Services": ( 200_000, 3_000_000),
    "Customer Care-Service Center":  (  30_000,   300_000),
    "Travel Agent-Ticketing":        ( 100_000, 5_000_000),
    "Telephone Service":             (  50_000,   500_000),
    "Photography":                   ( 100_000, 2_000_000),
    "Printing and Publishing":       (  30_000,   500_000),
    "Electrical":                    (  50_000, 1_000_000),
    "Landscaping Services":          ( 100_000, 2_000_000),
    "Storage":                       (  50_000,   500_000),
    "Mover":                         ( 100_000, 2_000_000),
    "Cargo Center":                  (  50_000, 1_000_000),
    "Commercial Services":           (  50_000, 1_000_000),
    "Rental and Leasing":            ( 100_000, 2_000_000),
    "Repair and Maintenance Services": ( 30_000,   500_000),
    "Tailor and Alteration":         (  30_000,   300_000),
    "Internet Cafe":                 (   5_000,    50_000),
    "Locksmiths and Security Systems Services": ( 50_000,   500_000),
    "Couriers":                      (  20_000,   300_000),
    "Cargo Transportation":          ( 100_000, 3_000_000),
    "Engineering and Scientific Services": ( 200_000, 5_000_000),
    "Modeling Agencies":             ( 100_000, 2_000_000),
    "B2B Sales and Services":        ( 100_000, 3_000_000),
    "Specialty Trade Contractors":   ( 100_000, 3_000_000),
    "Fulfillment and Distribution Center": ( 50_000, 1_000_000),
    "Outdoor Service":               (  50_000,   500_000),
    "Manufacturing":                 ( 100_000, 5_000_000),
    "Real Estate Services":          ( 200_000, 5_000_000),
    "Residential Area-Building":     ( 100_000, 2_000_000),
    "Warehouse":                     (  50_000, 1_000_000),
    "Facilities":                    (  50_000,   500_000),
    # ── Religion / community additions ───────────────────────────────────────
    "Mosque":                        (  20_000,   200_000),
    "Temple":                        (  20_000,   200_000),
    "Church":                        (  20_000,   200_000),
    "Religious Place":               (  20_000,   200_000),
    "Social Service":                (  20_000,   200_000),
    "Organizations and Societies":   (  20_000,   200_000),
    "Civic-Community Center":        (  20_000,   200_000),
    "Government Office":             (  20_000,   300_000),
    "Government or Community Facility": ( 20_000,   300_000),
    "Collective Community":          (  10_000,   100_000),
}

DEFAULT_VOLUME = (1, 5)
DEFAULT_AMOUNT = (50_000, 500_000)

# ──────────────────────────────────────────────────────────────────────────────
# INDONESIAN NATIONAL HOLIDAYS
# ──────────────────────────────────────────────────────────────────────────────

# Official public holidays + cuti bersama declared by the Indonesian government.
# Covers 2025–2026 to match typical simulation date ranges.
ID_NATIONAL_HOLIDAYS: dict[date, str] = {
    # ── 2025 ──────────────────────────────────────────────────────────────────
    date(2025,  1,  1): "Tahun Baru Masehi",
    date(2025,  1, 27): "Isra Mi'raj",
    date(2025,  1, 28): "Cuti Bersama Tahun Baru Imlek",
    date(2025,  1, 29): "Tahun Baru Imlek",
    date(2025,  3, 29): "Hari Suci Nyepi",
    date(2025,  3, 31): "Idul Fitri Hari Ke-1",
    date(2025,  4,  1): "Idul Fitri Hari Ke-2",
    date(2025,  4,  2): "Cuti Bersama Idul Fitri",
    date(2025,  4,  3): "Cuti Bersama Idul Fitri",
    date(2025,  4,  4): "Cuti Bersama Idul Fitri",
    date(2025,  4, 18): "Wafat Isa Almasih",
    date(2025,  5,  1): "Hari Buruh Internasional",
    date(2025,  5, 12): "Hari Raya Waisak",
    date(2025,  5, 29): "Kenaikan Isa Almasih",
    date(2025,  5, 30): "Cuti Bersama Kenaikan Isa Almasih",
    date(2025,  6,  1): "Hari Lahir Pancasila",
    date(2025,  6,  6): "Idul Adha",
    date(2025,  6, 27): "Tahun Baru Islam",
    date(2025,  8, 17): "Hari Kemerdekaan RI",
    date(2025,  9,  5): "Maulid Nabi Muhammad SAW",
    date(2025, 12, 25): "Hari Raya Natal",
    date(2025, 12, 26): "Cuti Bersama Natal",
    # ── 2026 ──────────────────────────────────────────────────────────────────
    date(2026,  1,  1): "Tahun Baru Masehi",
    date(2026,  1, 17): "Isra Mi'raj",
    date(2026,  2, 17): "Tahun Baru Imlek",
    date(2026,  3, 19): "Hari Suci Nyepi",
    date(2026,  3, 20): "Idul Fitri Hari Ke-1",
    date(2026,  3, 21): "Idul Fitri Hari Ke-2",
    date(2026,  3, 23): "Cuti Bersama Idul Fitri",
    date(2026,  3, 24): "Cuti Bersama Idul Fitri",
    date(2026,  4,  3): "Wafat Isa Almasih",
    date(2026,  5,  1): "Hari Buruh Internasional",
    date(2026,  5,  2): "Hari Raya Waisak",
    date(2026,  5, 14): "Kenaikan Isa Almasih",
    date(2026,  5, 27): "Idul Adha",
    date(2026,  6,  1): "Hari Lahir Pancasila",
    date(2026,  6, 17): "Tahun Baru Islam",
    date(2026,  8, 17): "Hari Kemerdekaan RI",
    date(2026,  8, 26): "Maulid Nabi Muhammad SAW",
    date(2026, 12, 25): "Hari Raya Natal",
}

# Categories that CLOSE on national holidays.
# F&B and wellness stay OPEN — they benefit from holiday foot traffic.
# Schools, retail, florists, dentists, and convention centres close.
HOLIDAY_CLOSED_CATEGORIES: frozenset[str] = frozenset({
    "Clothing and Accessories",
    "Women's Apparel",
    "Florist",
    "Dentist-Dental Office",
    "School",
    "Convention-Exhibition Center",
    # Education — all close on national holidays
    "Primary School",
    "Secondary School",
    "Education Facility",
    "Kindergarten and Childcare",
    "Language Studies",
    "Training and Development",
    "Coaching Institute",
    # Financial / professional — banks and offices close
    "Bank",
    "Post Office",
    "Government Office",
    "Government or Community Facility",
    "Tax Service",
    "Legal Services",
    "Attorney",
    "Management and Consulting Services",
    "Business Facility",
    "IT and Office Equipment Services",
    "Engineering and Scientific Services",
    "Financial Investment Firm",
    "Finance and Insurance",
    "Advertising-Marketing, PR and Market Research",
    "Human Resources and Recruiting Services",
})

# ──────────────────────────────────────────────────────────────────────────────
# HOLIDAY SURGE MULTIPLIERS
# ──────────────────────────────────────────────────────────────────────────────

# Maps each category to a surge group so multipliers can be defined per group
# rather than per individual category.
CATEGORY_SURGE_GROUP: dict[str, str] = {
    "Restaurant":                    "fnb",
    "Casual Dining":                 "fnb",
    "Fine Dining":                   "fnb",
    "Coffee Shop":                   "fnb",
    "Food-Beverage Specialty Store": "fnb",
    "Bakery and Baked Goods Store":  "fnb",
    "Butcher":                       "fnb",
    "Convenience Store":             "fnb",
    "Wine and Liquor":               "fnb",
    "Bar or Pub":                    "fnb",
    "Night Club":                    "events",
    "Clothing and Accessories":      "retail",
    "Women's Apparel":               "retail",
    "Children's Apparel":            "retail",
    "Specialty Store":               "retail",
    "Jeweler":                       "retail",
    "Sporting Goods Store":          "retail",
    "Pharmacy":                      "health",
    "Florist":                       "retail",
    "Hair and Beauty":               "beauty",
    "Barber":                        "beauty",
    "Wellness Center and Services":  "beauty",
    "Therapist":                     "beauty",
    "Fitness-Health Club":           "beauty",
    "Pet Care":                      "retail",
    "Dentist-Dental Office":         "health",
    "Medical Services-Clinics":      "health",
    "Hospital":                      "health",
    "School":                        "education",
    "Language Studies":              "education",
    "Training and Development":      "education",
    "Convention-Exhibition Center":  "events",
    "Car Wash-Detailing":            "automotive",
    "Dry Cleaning and Laundry":      "services",
    # ── F&B additions ────────────────────────────────────────────────────────
    "Tea House":                     "fnb",
    "Doughnut Shop":                 "fnb",
    "Cafeteria":                     "fnb",
    "Food Market-Stall":             "fnb",
    "Sweet Shop":                    "fnb",
    "Bistro":                        "fnb",
    "Dairy Goods":                   "fnb",
    "Coffee-Tea":                    "fnb",
    "Specialty Food Store":          "fnb",
    "Catering and Other Food Services": "fnb",
    "B2B Restaurant Services":       "fnb",
    "Fast Food":                     "fnb",
    "Deli":                          "fnb",
    "Take Out and Delivery Only":    "fnb",
    "Grocery":                       "fnb",
    "Bar ot Pub":                    "fnb",
    "Food Production":               "fnb",
    # ── Retail additions ─────────────────────────────────────────────────────
    "Furniture Store":               "retail",
    "Home Specialty Store":          "retail",
    "Consumer Electronics Store":    "retail",
    "Gift, Antique and Art":         "retail",
    "Pet Supply":                    "retail",
    "Toy Store":                     "retail",
    "Bookstore":                     "retail",
    "Arts and Crafts Supplies":      "retail",
    "Entertainment Electronics":     "retail",
    "Consumer Goods":                "retail",
    "Motorcycle Accessories":        "retail",
    "Glass and Window":              "retail",
    "Men's Apparel":                 "retail",
    "Wholesale Store":               "retail",
    "Specialty Clothing Store":      "retail",
    "Speciality Store":              "retail",
    "General Merchandise":           "retail",
    "Flowers and Jewelry":           "retail",
    "Hunting-Fishing Shop":          "retail",
    "Hardware, House and Garden":    "retail",
    "Garden Center":                 "retail",
    "Record, CD and Video":          "retail",
    "Drugstore":                     "retail",
    "Drugstore or Pharmacy":         "retail",
    "Auto Parts":                    "retail",
    "Paint Store":                   "retail",
    "Power Equipment Dealer":        "retail",
    "Home Improvement-Hardware Store": "retail",
    "Major Appliance":               "retail",
    "Shoes-Footwear":                "retail",
    "Computer and Software":         "retail",
    "Mobile Retailer":               "retail",
    "Market":                        "retail",
    "Shopping Mall":                 "retail",
    "Vaping Store":                  "retail",
    "Cigar and Tobacco Shop":        "retail",
    "Office Supply and Services Store": "retail",
    # ── Beauty / wellness additions ───────────────────────────────────────────
    "Hair Salon":                    "beauty",
    "Hair And Beauty":               "beauty",
    "Nail Salon":                    "beauty",
    "Body Piercing and Tattoos":     "beauty",
    "Chiropractor":                  "beauty",
    "Wedding Services and Bridal Studio": "beauty",
    # ── Health additions ─────────────────────────────────────────────────────
    "Veterinarian":                  "health",
    "Family-General Practice Physicians": "health",
    "Hospital or Health Care Facility": "health",
    "Healthcare and Healthcare Support Services": "health",
    "COVID-19 Testing Site":         "health",
    "Optical":                       "health",
    # ── Education additions ───────────────────────────────────────────────────
    "Primary School":                "education",
    "Secondary School":              "education",
    "Education Facility":            "education",
    "Kindergarten and Childcare":    "education",
    "Coaching Institute":            "education",
    # ── Entertainment additions ───────────────────────────────────────────────
    "Cinema":                        "entertainment",
    "Karaoke":                       "entertainment",
    "Nightlife-Entertainment":       "entertainment",
    "Live Entertainment-Music":      "entertainment",
    "Theatre, Music and Culture":    "entertainment",
    "Casino":                        "entertainment",
    "Leisure":                       "entertainment",
    "Video Arcade-Game Room":        "entertainment",
    "Billiards-Pool Hall":           "entertainment",
    "Entertainment and Recreation":  "entertainment",
    "Race Track":                    "entertainment",
    "Tourist Attraction":            "entertainment",
    "Aquarium":                      "entertainment",
    "Museum":                        "entertainment",
    "Sporting Instruction and Camps":"entertainment",
    "Fine Arts":                     "entertainment",
    "Adult Entertainment":           "entertainment",
    "Video and Game Rental":         "entertainment",
    # ── Events / sports additions ─────────────────────────────────────────────
    "Event Spaces":                  "events",
    "Sports Complex-Stadium":        "events",
    "Sports Facility-Venue":         "events",
    "Sports Field":                  "events",
    "Golf Course":                   "events",
    "Golf Practice Range":           "events",
    "Swimming Pool":                 "events",
    "Basketball":                    "events",
    "Running Track":                 "events",
    "Outdoor-Recreation":            "events",
    "Park-Recreation Area":          "events",
    "Garden":                        "events",
    # ── Hospitality additions (new group) ────────────────────────────────────
    "Hotel":                         "hospitality",
    "Guest House":                   "hospitality",
    "Hotel or Motel":                "hospitality",
    "Lodging":                       "hospitality",
    "Bed and Breakfast":             "hospitality",
    "Hostel":                        "hospitality",
    "Clubhouse":                     "hospitality",
    "Apartment Rental-Flat Rental":  "hospitality",
    # ── Automotive additions (new group) ─────────────────────────────────────
    "Car Repair-Service":            "automotive",
    "Car Repair":                    "automotive",
    "Motorcycle Dealership":         "automotive",
    "Motorcycle Service and Maintenance": "automotive",
    "Truck Repair":                  "automotive",
    "Bicycle and Bicycle Accessories Shop": "automotive",
    "Bicycle Service and Maintenance": "automotive",
    "Rental Car Agency":             "automotive",
    "EV Charging Station":           "automotive",
    "Petrol-Gasoline Station":       "automotive",
    "Automobile Dealership-New Cars":"automotive",
    "Tire Repair":                   "automotive",
    # ── Services additions (new group) ───────────────────────────────────────
    "Bank":                          "services",
    "Post Office":                   "services",
    "Money Transferring Service":    "services",
    "Finance and Insurance":         "services",
    "Financial Investment Firm":     "services",
    "Pawnshop":                      "services",
    "Legal Services":                "services",
    "Attorney":                      "services",
    "Tax Service":                   "services",
    "Property Management":           "services",
    "Management and Consulting Services": "services",
    "Business Facility":             "services",
    "Advertising-Marketing, PR and Market Research": "services",
    "Human Resources and Recruiting Services": "services",
    "IT and Office Equipment Services": "services",
    "Customer Care-Service Center":  "services",
    "Travel Agent-Ticketing":        "services",
    "Telephone Service":             "services",
    "Photography":                   "services",
    "Printing and Publishing":       "services",
    "Electrical":                    "services",
    "Landscaping Services":          "services",
    "Storage":                       "services",
    "Mover":                         "services",
    "Cargo Center":                  "services",
    "Commercial Services":           "services",
    "Rental and Leasing":            "services",
    "Repair and Maintenance Services": "services",
    "Engineering and Scientific Services": "services",
    "Modeling Agencies":             "services",
    "B2B Sales and Services":        "services",
    "Consumer Services":             "services",
    "Interior and Exterior Design":  "services",
    "Business Service":              "services",
    "Couriers":                      "services",
    "Cargo Transportation":          "services",
    "Specialty Trade Contractors":   "services",
    "Fulfillment and Distribution Center": "services",
    "Tailor and Alteration":         "services",
    "Internet Cafe":                 "services",
    "Locksmiths and Security Systems Services": "services",
    "Mobile Service Center":         "services",
    "Repair Service":                "services",
    "Warehouse":                     "services",
    "Facilities":                    "services",
    "Outdoor Service":               "services",
    "Manufacturing":                 "services",
    "Real Estate Services":          "services",
    "Residential Area-Building":     "services",
    # ── Community / religion (new group) ────────────────────────────────────
    "Mosque":                        "community",
    "Temple":                        "community",
    "Church":                        "community",
    "Religious Place":               "community",
    "Social Service":                "community",
    "Organizations and Societies":   "community",
    "Civic-Community Center":        "community",
    "Collective Community":          "community",
    "Government Office":             "community",
    "Government or Community Facility": "community",
}

# Each entry: (start_date, end_date, event_label, {group: multiplier})
# Only groups meaningfully affected by the event are listed;
# any group absent from the dict gets multiplier 1.0 (no change).
#
# Groups and their typical behaviour:
#   fnb       — most holidays increase dining out
#   retail    — surges before Eid & Christmas; quiet on religious holidays
#   beauty    — surges before Eid (salon prep); mild boost on long weekends
#   health    — dentists not affected by celebrations; slightly down on holidays
#   education — closed most holidays; effectively 0 on school breaks
#   events    — spikes on national celebrations and long weekends
HOLIDAY_SURGE_PERIODS: list[tuple] = [
    # ── Idul Fitri 2026 (2026-03-20 / 21) ────────────────────────────────────
    # Pre-Lebaran shopping frenzy: H-10 → H-1
    (date(2026, 3, 10), date(2026, 3, 19), "Pre-Idul Fitri",
     {"fnb": 1.5, "retail": 2.8, "beauty": 2.2, "health": 0.7, "education": 0.5}),
    # Post-Lebaran return & family visits: H+3 → H+7
    (date(2026, 3, 24), date(2026, 3, 28), "Post-Idul Fitri",
     {"fnb": 1.6, "retail": 1.3, "beauty": 1.3, "health": 0.8}),

    # ── Idul Adha 2026 (2026-05-27) ──────────────────────────────────────────
    (date(2026, 5, 24), date(2026, 5, 28), "Idul Adha",
     {"fnb": 1.4, "events": 1.2}),

    # ── Hari Lahir Pancasila 2026 (2026-06-01) ────────────────────────────────
    (date(2026, 5, 30), date(2026, 6, 2), "Pancasila Day",
     {"fnb": 1.2, "events": 1.3}),

    # ── Chinese New Year 2026 (2026-02-17) ───────────────────────────────────
    (date(2026, 2, 14), date(2026, 2, 19), "Imlek",
     {"fnb": 1.7, "retail": 1.5, "beauty": 1.4, "events": 1.3}),

    # ── Indonesian Independence Day 2026 (2026-08-17) ─────────────────────────
    (date(2026, 8, 15), date(2026, 8, 19), "HUT RI",
     {"fnb": 1.3, "events": 1.5, "retail": 1.2}),

    # ── Waisak 2026 (2026-05-02) ─────────────────────────────────────────────
    (date(2026, 4, 30), date(2026, 5, 3), "Waisak",
     {"fnb": 1.2, "events": 1.2}),

    # ── Christmas 2026 (2026-12-25) ───────────────────────────────────────────
    (date(2026, 12, 22), date(2026, 12, 28), "Natal",
     {"fnb": 1.5, "retail": 1.7, "beauty": 1.3, "events": 1.6}),

    # ── New Year 2026 → 2027 ─────────────────────────────────────────────────
    (date(2026, 12, 29), date(2027, 1, 2), "Tahun Baru",
     {"fnb": 1.7, "retail": 1.4, "beauty": 1.3, "events": 1.8}),

    # ── New Year 2025 → 2026 ─────────────────────────────────────────────────
    (date(2025, 12, 29), date(2026, 1, 3), "Tahun Baru",
     {"fnb": 1.7, "retail": 1.4, "beauty": 1.3, "events": 1.8}),

    # ── Chinese New Year 2025 (2025-01-29) ───────────────────────────────────
    (date(2025, 1, 25), date(2025, 1, 31), "Imlek",
     {"fnb": 1.7, "retail": 1.5, "beauty": 1.4, "events": 1.3}),

    # ── Idul Fitri 2025 (2025-03-31 / 04-01) ────────────────────────────────
    (date(2025, 3, 21), date(2025, 3, 30), "Pre-Idul Fitri",
     {"fnb": 1.5, "retail": 2.8, "beauty": 2.2, "health": 0.7, "education": 0.5}),
    (date(2025, 4,  3), date(2025, 4,  7), "Post-Idul Fitri",
     {"fnb": 1.6, "retail": 1.3, "beauty": 1.3, "health": 0.8}),

    # ── Christmas 2025 (2025-12-25) ───────────────────────────────────────────
    (date(2025, 12, 22), date(2025, 12, 28), "Natal",
     {"fnb": 1.5, "retail": 1.7, "beauty": 1.3, "events": 1.6,
      "hospitality": 1.5, "entertainment": 1.4}),

    # ── New groups: hospitality surge on Eid + year-end travel ───────────────
    (date(2026, 3, 20), date(2026, 3, 28), "Idul Fitri travel",
     {"hospitality": 1.8, "entertainment": 1.5, "events": 1.3}),
    (date(2025, 3, 31), date(2025, 4,  7), "Idul Fitri travel",
     {"hospitality": 1.8, "entertainment": 1.5, "events": 1.3}),
    (date(2026, 12, 22), date(2027, 1,  3), "Year-end travel",
     {"hospitality": 1.6, "entertainment": 1.6, "events": 1.5}),
    (date(2025, 12, 22), date(2026, 1,  3), "Year-end travel",
     {"hospitality": 1.6, "entertainment": 1.6, "events": 1.5}),

    # ── Automotive: pre-Eid motorcycle/car buying surge ──────────────────────
    (date(2026, 3,  5), date(2026, 3, 19), "Pre-Eid automotive",
     {"automotive": 1.6, "retail": 1.3}),
    (date(2025, 3, 21), date(2025, 3, 30), "Pre-Eid automotive",
     {"automotive": 1.6, "retail": 1.3}),

    # ── Services: holiday suppression (banks/offices closed) ─────────────────
    (date(2026, 3, 20), date(2026, 3, 21), "Idul Fitri closure",
     {"services": 0.2, "education": 0.0, "community": 0.3}),
    (date(2025, 3, 31), date(2025, 4,  1), "Idul Fitri closure",
     {"services": 0.2, "education": 0.0, "community": 0.3}),
]

# ── Pre-closure volume decay ───────────────────────────────────────────────────
# When a merchant has a closed_from date, transaction volume tapers
# in the weeks leading up to closure.  Pairs: (days_to_close, multiplier).
# Evaluated from smallest to largest threshold.
CLOSURE_DECLINE_STEPS: list[tuple[int, float]] = [
    (1,  0.10),   # last day
    (7,  0.25),   # within 1 week
    (14, 0.50),   # 1–2 weeks out
    (30, 0.70),   # 2–4 weeks out
    (60, 0.85),   # 1–2 months out
]

# ──────────────────────────────────────────────────────────────────────────────
# QRIS PROFILES
# ──────────────────────────────────────────────────────────────────────────────

# Probability a given transaction uses QRIS (vs EDC card swipe/tap).
# Everyday F&B/services lean heavily QRIS; luxury goods lean card.
QRIS_PROBABILITY = {
    "Coffee Shop":                   0.70,
    "Food-Beverage Specialty Store": 0.68,
    "Bakery and Baked Goods Store":  0.68,
    "Convenience Store":             0.67,
    "Butcher":                       0.65,
    "Restaurant":                    0.65,
    "Casual Dining":                 0.62,
    "Bar or Pub":                    0.60,
    "Night Club":                    0.58,
    "Florist":                       0.58,
    "Pharmacy":                      0.58,
    "Barber":                        0.58,
    "Hair and Beauty":               0.55,
    "Dry Cleaning and Laundry":      0.55,
    "Car Wash-Detailing":            0.52,
    "Wellness Center and Services":  0.52,
    "Therapist":                     0.50,
    "Fitness-Health Club":           0.50,
    "Medical Services-Clinics":      0.48,
    "Pet Care":                      0.48,
    "Repair Service":                0.48,
    "Mobile Service Center":         0.48,
    "Fine Dining":                   0.45,
    "School":                        0.45,
    "Language Studies":              0.45,
    "Training and Development":      0.42,
    "Convention-Exhibition Center":  0.40,
    "Dentist-Dental Office":         0.35,
    "Hospital":                      0.35,
    "Sporting Goods Store":          0.32,
    "Specialty Store":               0.30,
    "Women's Apparel":               0.28,
    "Children's Apparel":            0.28,
    "Clothing and Accessories":      0.25,
    "Jeweler":                       0.22,
    "Wine and Liquor":               0.30,
    # ── F&B additions ────────────────────────────────────────────────────────
    "Tea House":                     0.68,
    "Food Market-Stall":             0.72,
    "Doughnut Shop":                 0.65,
    "Sweet Shop":                    0.65,
    "Cafeteria":                     0.62,
    "Dairy Goods":                   0.60,
    "Bistro":                        0.60,
    "Coffee-Tea":                    0.70,
    "Specialty Food Store":          0.58,
    "Catering and Other Food Services": 0.50,
    "Fast Food":                     0.65,
    "Deli":                          0.60,
    "Take Out and Delivery Only":    0.62,
    "Grocery":                       0.60,
    "Bar ot Pub":                    0.45,
    "Food Production":               0.40,
    "B2B Restaurant Services":       0.35,
    # ── Retail additions ─────────────────────────────────────────────────────
    "Furniture Store":               0.28,
    "Home Specialty Store":          0.35,
    "Consumer Electronics Store":    0.30,
    "Gift, Antique and Art":         0.40,
    "Pet Supply":                    0.45,
    "Toy Store":                     0.42,
    "Bookstore":                     0.50,
    "Arts and Crafts Supplies":      0.48,
    "Entertainment Electronics":     0.30,
    "Consumer Goods":                0.45,
    "Motorcycle Accessories":        0.40,
    "Men's Apparel":                 0.28,
    "Wholesale Store":               0.25,
    "Specialty Clothing Store":      0.35,
    "Speciality Store":              0.35,
    "General Merchandise":           0.48,
    "Flowers and Jewelry":           0.45,
    "Hunting-Fishing Shop":          0.35,
    "Hardware, House and Garden":    0.35,
    "Garden Center":                 0.40,
    "Record, CD and Video":          0.40,
    "Drugstore":                     0.58,
    "Drugstore or Pharmacy":         0.58,
    "Auto Parts":                    0.35,
    "Paint Store":                   0.32,
    "Power Equipment Dealer":        0.28,
    "Vaping Store":                  0.45,
    "Cigar and Tobacco Shop":        0.42,
    "Shoes-Footwear":                0.35,
    "Computer and Software":         0.28,
    "Mobile Retailer":               0.35,
    "Market":                        0.62,
    "Shopping Mall":                 0.40,
    "Office Supply and Services Store": 0.38,
    # ── Beauty additions ─────────────────────────────────────────────────────
    "Hair Salon":                    0.55,
    "Hair And Beauty":               0.55,
    "Nail Salon":                    0.58,
    "Body Piercing and Tattoos":     0.50,
    "Chiropractor":                  0.40,
    "Wedding Services and Bridal Studio": 0.30,
    # ── Health additions ─────────────────────────────────────────────────────
    "Veterinarian":                  0.38,
    "Family-General Practice Physicians": 0.42,
    "Hospital or Health Care Facility": 0.30,
    "Healthcare and Healthcare Support Services": 0.35,
    "COVID-19 Testing Site":         0.45,
    "Optical":                       0.32,
    # ── Education additions ───────────────────────────────────────────────────
    "Primary School":                0.45,
    "Secondary School":              0.45,
    "Education Facility":            0.45,
    "Kindergarten and Childcare":    0.42,
    "Coaching Institute":            0.40,
    # ── Entertainment additions ───────────────────────────────────────────────
    "Cinema":                        0.55,
    "Karaoke":                       0.50,
    "Nightlife-Entertainment":       0.45,
    "Live Entertainment-Music":      0.45,
    "Theatre, Music and Culture":    0.42,
    "Casino":                        0.20,
    "Leisure":                       0.48,
    "Video Arcade-Game Room":        0.55,
    "Billiards-Pool Hall":           0.52,
    "Entertainment and Recreation":  0.50,
    "Race Track":                    0.35,
    "Tourist Attraction":            0.48,
    "Aquarium":                      0.45,
    "Museum":                        0.42,
    "Sporting Instruction and Camps":0.45,
    "Fine Arts":                     0.38,
    "Adult Entertainment":           0.35,
    "Video and Game Rental":         0.45,
    # ── Events / sports additions ─────────────────────────────────────────────
    "Event Spaces":                  0.40,
    "Sports Complex-Stadium":        0.45,
    "Sports Facility-Venue":         0.45,
    "Sports Field":                  0.48,
    "Golf Course":                   0.25,
    "Golf Practice Range":           0.30,
    "Swimming Pool":                 0.50,
    "Basketball":                    0.52,
    "Running Track":                 0.50,
    "Outdoor-Recreation":            0.48,
    "Park-Recreation Area":          0.52,
    "Garden":                        0.45,
    # ── Hospitality additions ────────────────────────────────────────────────
    "Hotel":                         0.35,
    "Guest House":                   0.45,
    "Hotel or Motel":                0.35,
    "Lodging":                       0.40,
    "Bed and Breakfast":             0.42,
    "Hostel":                        0.48,
    "Clubhouse":                     0.40,
    "Apartment Rental-Flat Rental":  0.38,
    # ── Automotive additions ──────────────────────────────────────────────────
    "Car Repair-Service":            0.42,
    "Car Repair":                    0.42,
    "Motorcycle Dealership":         0.28,
    "Motorcycle Service and Maintenance": 0.40,
    "Truck Repair":                  0.32,
    "Bicycle and Bicycle Accessories Shop": 0.45,
    "Bicycle Service and Maintenance": 0.45,
    "Rental Car Agency":             0.35,
    "EV Charging Station":           0.55,
    "Petrol-Gasoline Station":       0.50,
    "Automobile Dealership-New Cars":0.22,
    "Tire Repair":                   0.42,
    # ── Services additions ────────────────────────────────────────────────────
    "Bank":                          0.20,
    "Post Office":                   0.35,
    "Money Transferring Service":    0.30,
    "Finance and Insurance":         0.25,
    "Financial Investment Firm":     0.20,
    "Pawnshop":                      0.40,
    "Legal Services":                0.20,
    "Attorney":                      0.18,
    "Tax Service":                   0.25,
    "Property Management":           0.22,
    "Management and Consulting Services": 0.22,
    "Business Facility":             0.25,
    "Advertising-Marketing, PR and Market Research": 0.25,
    "Human Resources and Recruiting Services": 0.22,
    "Customer Care-Service Center":  0.35,
    "Travel Agent-Ticketing":        0.35,
    "Telephone Service":             0.40,
    "Photography":                   0.42,
    "Printing and Publishing":       0.38,
    "Electrical":                    0.35,
    "Landscaping Services":          0.32,
    "Storage":                       0.30,
    "Mover":                         0.30,
    "Cargo Center":                  0.28,
    "Commercial Services":           0.28,
    "Rental and Leasing":            0.35,
    "Repair and Maintenance Services": 0.40,
    "Tailor and Alteration":         0.48,
    "Internet Cafe":                 0.55,
    "Locksmiths and Security Systems Services": 0.32,
    "Couriers":                      0.35,
    "Cargo Transportation":          0.28,
    "IT and Office Equipment Services": 0.30,
    "Interior and Exterior Design":  0.28,
    "Business Service":              0.28,
    "Consumer Services":             0.40,
    "Engineering and Scientific Services": 0.22,
    "Modeling Agencies":             0.28,
    "B2B Sales and Services":        0.25,
    "Specialty Trade Contractors":   0.30,
    "Fulfillment and Distribution Center": 0.25,
    "Outdoor Service":               0.30,
    "Manufacturing":                 0.22,
    "Real Estate Services":          0.22,
    "Residential Area-Building":     0.25,
    "Warehouse":                     0.22,
    "Facilities":                    0.28,
    # ── Religion / community additions ───────────────────────────────────────
    "Mosque":                        0.30,
    "Temple":                        0.30,
    "Church":                        0.30,
    "Religious Place":               0.30,
    "Social Service":                0.30,
    "Organizations and Societies":   0.28,
    "Civic-Community Center":        0.32,
    "Government Office":             0.28,
    "Government or Community Facility": 0.28,
    "Collective Community":          0.30,
}

DEFAULT_QRIS_PROB = 0.45

# Relative weights for QRIS issuer selection.
# Bank QRIS collectively > fintech (BCA mobile banking is the largest).
# Among fintech, GoPay dominates by a wide margin.
QRIS_ISSUER_WEIGHTS = {
    "BCA-QRIS":   30,   # largest bank app user base
    "MDR-QRIS":   12,   # second bank
    "BRI-QRIS":    8,   # strong retail/unbanked reach
    "BNI-QRIS":    7,   # government-linked bank
    "GOPAY":      25,   # fintech leader, clear #1
    "SHOPEEPAY":   8,   # second fintech
    "OVO":         6,   # third
    "DANA":        3,   # fourth
    "LINKAJA":     1,   # smallest share
}
# Bank total ≈ 57 %  |  Fintech total ≈ 43 %  |  GoPay ≈ 60 % of fintech

# ──────────────────────────────────────────────────────────────────────────────
# RESPONSE CODE PROFILES  (ISO 8583)
# ──────────────────────────────────────────────────────────────────────────────

# EDC card response codes — full ISO 8583 set applies
RESPONSE_CODE_POPULATION = ["00", "05", "51", "91", "54", "61"]
RESPONSE_CODE_WEIGHTS    = [  88,    4,    4,    2,    1,    1]

# QRIS response codes — balance is shown before confirmation so the customer
# can never be declined for insufficient funds, limit breach, or card issues.
# Only technical/network failures can cause a QRIS decline, and those are
# automatically reversed by the network (no REFUND record generated in EDC).
QRIS_RESPONSE_CODE_POPULATION = ["00", "91", "05"]
QRIS_RESPONSE_CODE_WEIGHTS    = [ 97,    2,    1]

RESPONSE_MESSAGES = {
    "00": "APPROVED",
    "05": "DECLINED - DO NOT HONOR",
    "51": "DECLINED - INSUFFICIENT FUNDS",
    "91": "DECLINED - CONNECTION TIMEOUT",
    "54": "DECLINED - EXPIRED CARD",
    "61": "DECLINED - EXCEEDS WITHDRAWAL LIMIT",
    "14": "DECLINED - INVALID CARD NUMBER",
}

# ──────────────────────────────────────────────────────────────────────────────
# DEFAULT OPERATING HOURS (fallback when CSV has no hours data)
# ──────────────────────────────────────────────────────────────────────────────

CATEGORY_DEFAULT_HOURS: dict[str, tuple[time, time] | None] = {
    # ── F&B ──────────────────────────────────────────────────────────────────
    "Coffee Shop":                   (time( 7, 0), time(22, 0)),
    "Restaurant":                    (time(10, 0), time(22, 0)),
    "Casual Dining":                 (time(10, 0), time(21, 0)),
    "Fine Dining":                   (time(11, 0), time(22, 0)),
    "Food-Beverage Specialty Store": (time( 9, 0), time(21, 0)),
    "Bakery and Baked Goods Store":  (time( 7, 0), time(20, 0)),
    "Butcher":                       (time( 7, 0), time(17, 0)),
    "Convenience Store":             (time( 7, 0), time(23, 0)),
    "Wine and Liquor":               (time(10, 0), time(21, 0)),
    "Bar or Pub":                    (time(17, 0), time(23, 0)),
    "Night Club":                    (time(20, 0), time(23, 0)),
    # ── Retail ───────────────────────────────────────────────────────────────
    "Clothing and Accessories":      (time(10, 0), time(21, 0)),
    "Women's Apparel":               (time(10, 0), time(21, 0)),
    "Children's Apparel":            (time(10, 0), time(21, 0)),
    "Specialty Store":               (time( 9, 0), time(21, 0)),
    "Jeweler":                       (time(10, 0), time(20, 0)),
    "Sporting Goods Store":          (time( 9, 0), time(21, 0)),
    "Pharmacy":                      (time( 8, 0), time(22, 0)),
    "Florist":                       (time( 9, 0), time(18, 0)),
    # ── Beauty / wellness ────────────────────────────────────────────────────
    "Hair and Beauty":               (time( 9, 0), time(20, 0)),
    "Barber":                        (time( 9, 0), time(20, 0)),
    "Wellness Center and Services":  (time( 9, 0), time(21, 0)),
    "Therapist":                     (time( 9, 0), time(21, 0)),
    "Fitness-Health Club":           (time( 6, 0), time(22, 0)),
    "Pet Care":                      (time( 9, 0), time(18, 0)),
    # ── Health ───────────────────────────────────────────────────────────────
    "Dentist-Dental Office":         (time( 9, 0), time(17, 0)),
    "Medical Services-Clinics":      (time( 8, 0), time(17, 0)),
    "Hospital":                      (time( 8, 0), time(20, 0)),
    # ── Education ────────────────────────────────────────────────────────────
    "School":                        (time( 8, 0), time(16, 0)),
    "Language Studies":              (time( 9, 0), time(20, 0)),
    "Training and Development":      (time( 8, 0), time(17, 0)),
    # ── Services ─────────────────────────────────────────────────────────────
    "Car Wash-Detailing":            (time( 8, 0), time(18, 0)),
    "Dry Cleaning and Laundry":      (time( 8, 0), time(18, 0)),
    "Repair Service":                (time( 9, 0), time(18, 0)),
    "Mobile Service Center":         (time( 9, 0), time(20, 0)),
    "IT and Office Equipment Services": (time( 8, 0), time(17, 0)),
    "Business Service":              (time( 8, 0), time(17, 0)),
    "Consumer Services":             (time( 9, 0), time(18, 0)),
    "Interior and Exterior Design":  (time( 9, 0), time(17, 0)),
    # ── Events / other ───────────────────────────────────────────────────────
    "Convention-Exhibition Center":  (time( 8, 0), time(20, 0)),
    # ── Automotive / misc ────────────────────────────────────────────────────
    "Automobile Dealership-New Cars": (time( 9, 0), time(17, 0)),
    "Tire Repair":                   (time( 8, 0), time(17, 0)),
    # ── Recreation ───────────────────────────────────────────────────────────
    "Billiards-Pool Hall":           (time(14, 0), time(23, 0)),
    "Video Arcade-Game Room":        (time(10, 0), time(22, 0)),
    "Golf Course":                   (time( 6, 0), time(18, 0)),
    # ── Other ────────────────────────────────────────────────────────────────
    "Couriers":                      (time( 8, 0), time(17, 0)),
    "Real Estate Services":          (time( 9, 0), time(17, 0)),
    "Residential Area-Building":     (time( 9, 0), time(17, 0)),
    "Floor and Carpet":              (time( 9, 0), time(18, 0)),
    "Home Improvement-Hardware Store": (time( 8, 0), time(18, 0)),
    "Major Appliance":               (time( 9, 0), time(20, 0)),
    "Office Supply and Services Store": (time( 8, 0), time(17, 0)),
    "Bus Stop":                      None,
    # ── F&B (additional) ─────────────────────────────────────────────────────
    "Fast Food":                     (time( 8, 0), time(22, 0)),
    "Deli":                          (time( 8, 0), time(21, 0)),
    "Take Out and Delivery Only":    (time( 9, 0), time(22, 0)),
    "Grocery":                       (time( 8, 0), time(22, 0)),
    "Cigar and Tobacco Shop":        (time(10, 0), time(22, 0)),
    "Vaping Store":                  (time(10, 0), time(22, 0)),
    # ── Retail (additional) ──────────────────────────────────────────────────
    "Shoes-Footwear":                (time(10, 0), time(21, 0)),
    "Computer and Software":         (time( 9, 0), time(20, 0)),
    "Mobile Retailer":               (time( 9, 0), time(20, 0)),
    "Optical":                       (time( 9, 0), time(17, 0)),
    # ── Hospitality / entertainment ──────────────────────────────────────────
    "Hotel":                         (time( 6, 0), time(23, 0)),
    "Karaoke":                       (time(14, 0), time(23, 0)),
    "Transportation Service":        (time( 7, 0), time(22, 0)),
    "Wedding Services and Bridal Studio": (time(10, 0), time(18, 0)),
    # ── F&B (additional) ─────────────────────────────────────────────────────
    "Tea House":                          (time( 8, 0), time(21, 0)),
    "Doughnut Shop":                      (time( 7, 0), time(20, 0)),
    "Cafeteria":                          (time( 7, 0), time(17, 0)),
    "Food Market-Stall":                  (time( 6, 0), time(17, 0)),
    "Food Production":                    (time( 8, 0), time(17, 0)),
    # ── Retail (additional) ──────────────────────────────────────────────────
    "Furniture Store":                    (time( 9, 0), time(20, 0)),
    "Home Specialty Store":               (time( 9, 0), time(20, 0)),
    "Consumer Electronics Store":         (time(10, 0), time(21, 0)),
    "Gift, Antique and Art":              (time(10, 0), time(19, 0)),
    "Pet Supply":                         (time( 9, 0), time(20, 0)),
    "Toy Store":                          (time(10, 0), time(21, 0)),
    "Auto Parts":                         (time( 8, 0), time(17, 0)),
    "Paint Store":                        (time( 8, 0), time(17, 0)),
    "Power Equipment Dealer":             (time( 8, 0), time(17, 0)),
    "Specialty Clothing Store":           (time(10, 0), time(21, 0)),
    "Speciality Store":                   (time( 9, 0), time(21, 0)),  # spelling variant
    "Drugstore":                          (time( 8, 0), time(22, 0)),
    "Drugstore or Pharmacy":              (time( 8, 0), time(22, 0)),
    # ── Beauty / wellness (additional) ───────────────────────────────────────
    "Hair Salon":                         (time( 9, 0), time(20, 0)),
    "Hair And Beauty":                    (time( 9, 0), time(20, 0)),  # case variant
    "Nail Salon":                         (time( 9, 0), time(20, 0)),
    "Body Piercing and Tattoos":          (time(11, 0), time(21, 0)),
    # ── Automotive / transport ───────────────────────────────────────────────
    "Motorcycle Dealership":              (time( 9, 0), time(17, 0)),
    "Motorcycle Service and Maintenance": (time( 8, 0), time(17, 0)),
    "Truck Repair":                       (time( 8, 0), time(17, 0)),
    "Bicycle and Bicycle Accessories Shop": (time( 9, 0), time(18, 0)),
    "Cargo Transportation":               (time( 8, 0), time(17, 0)),
    # ── Services (additional) ────────────────────────────────────────────────
    "Tailor and Alteration":              (time( 9, 0), time(18, 0)),
    "Customer Care-Service Center":       (time( 9, 0), time(18, 0)),
    "Travel Agent-Ticketing":             (time( 9, 0), time(18, 0)),
    "Telephone Service":                  (time( 9, 0), time(18, 0)),
    "Photography":                        (time( 9, 0), time(20, 0)),
    # ── Business / professional ──────────────────────────────────────────────
    "Business Facility":                  (time( 8, 0), time(17, 0)),
    "Management and Consulting Services": (time( 8, 0), time(17, 0)),
    "Advertising-Marketing, PR and Market Research": (time( 8, 0), time(17, 0)),
    "Finance and Insurance":              (time( 8, 0), time(17, 0)),
    "Financial Investment Firm":          (time( 8, 0), time(17, 0)),
    "Human Resources and Recruiting Services": (time( 8, 0), time(17, 0)),
    "Legal Services":                     (time( 8, 0), time(17, 0)),
    "Attorney":                           (time( 8, 0), time(17, 0)),
    "Tax Service":                        (time( 8, 0), time(17, 0)),
    "Property Management":                (time( 8, 0), time(17, 0)),
    # ── Health (additional) ──────────────────────────────────────────────────
    "Healthcare and Healthcare Support Services": (time( 8, 0), time(17, 0)),
    "Specialty Trade Contractors":        (time( 8, 0), time(17, 0)),
    # ── Recreation / entertainment (additional) ──────────────────────────────
    "Entertainment and Recreation":       (time(10, 0), time(22, 0)),
    "Sports Complex-Stadium":             (time( 7, 0), time(22, 0)),
    "Shopping Mall":                      (time(10, 0), time(22, 0)),
    "Outdoor-Recreation":                 (time( 7, 0), time(18, 0)),
    "Video and Game Rental":              (time(10, 0), time(21, 0)),
    "Fine Arts":                          (time(10, 0), time(19, 0)),
    # ── Education / community ────────────────────────────────────────────────
    "Kindergarten and Childcare":         (time( 7, 0), time(16, 0)),
    "Mosque":                             (time( 8, 0), time(17, 0)),
    # ── categories.csv additions ─────────────────────────────────────────────
    # F&B
    "Bistro":                             (time(10, 0), time(22, 0)),
    "Coffee-Tea":                         (time( 7, 0), time(22, 0)),
    "Sweet Shop":                         (time( 9, 0), time(21, 0)),
    "Dairy Goods":                        (time( 7, 0), time(20, 0)),
    "Specialty Food Store":               (time( 9, 0), time(21, 0)),
    "Catering and Other Food Services":   (time( 8, 0), time(17, 0)),
    "B2B Restaurant Services":            (time( 8, 0), time(17, 0)),
    # Retail
    "Bookstore":                          (time( 9, 0), time(21, 0)),
    "Entertainment Electronics":          (time(10, 0), time(21, 0)),
    "Consumer Goods":                     (time( 9, 0), time(21, 0)),
    "Motorcycle Accessories":             (time( 8, 0), time(17, 0)),
    "Arts and Crafts Supplies":           (time( 9, 0), time(20, 0)),
    "Record, CD and Video":               (time(10, 0), time(20, 0)),
    "General Merchandise":                (time( 9, 0), time(21, 0)),
    "Flowers and Jewelry":                (time( 9, 0), time(19, 0)),
    "Hunting-Fishing Shop":               (time( 9, 0), time(17, 0)),
    "Glass and Window":                   (time( 8, 0), time(17, 0)),
    "Hardware, House and Garden":         (time( 8, 0), time(18, 0)),
    "Garden Center":                      (time( 8, 0), time(18, 0)),
    "Men's Apparel":                      (time(10, 0), time(21, 0)),
    "Wholesale Store":                    (time( 8, 0), time(17, 0)),
    # Beauty / wellness
    "Chiropractor":                       (time( 9, 0), time(17, 0)),
    # Automotive / transport
    "Car Repair-Service":                 (time( 8, 0), time(17, 0)),
    "Car Repair":                         (time( 8, 0), time(17, 0)),
    "Bicycle Service and Maintenance":    (time( 9, 0), time(17, 0)),
    "Rental Car Agency":                  (time( 7, 0), time(20, 0)),
    "EV Charging Station":                (time( 6, 0), time(23, 0)),
    "Petrol-Gasoline Station":            (time( 6, 0), time(23, 0)),
    "Bar ot Pub":                         (time(17, 0), time(23, 0)),  # typo variant of Bar or Pub
    # Services
    "Bank":                               (time( 8, 0), time(16, 0)),
    "ATM":                                None,
    "Post Office":                        (time( 8, 0), time(15, 0)),
    "Money Transferring Service":         (time( 8, 0), time(17, 0)),
    "Internet Cafe":                      (time(10, 0), time(22, 0)),
    "Pawnshop":                           (time( 9, 0), time(17, 0)),
    "Locksmiths and Security Systems Services": (time( 8, 0), time(17, 0)),
    "Printing and Publishing":            (time( 8, 0), time(17, 0)),
    "Electrical":                         (time( 8, 0), time(17, 0)),
    "Landscaping Services":               (time( 8, 0), time(17, 0)),
    "Outdoor Service":                    (time( 8, 0), time(17, 0)),
    "Mover":                              (time( 8, 0), time(17, 0)),
    "Storage":                            (time( 8, 0), time(17, 0)),
    "Cargo Center":                       (time( 8, 0), time(17, 0)),
    "Commercial Services":                (time( 8, 0), time(17, 0)),
    "Rental and Leasing":                 (time( 9, 0), time(18, 0)),
    "Repair and Maintenance Services":    (time( 8, 0), time(17, 0)),
    # Professional / business
    "Modeling Agencies":                  (time( 9, 0), time(17, 0)),
    "Engineering and Scientific Services":(time( 8, 0), time(17, 0)),
    "B2B Sales and Services":             (time( 8, 0), time(17, 0)),
    "Coaching Institute":                 (time( 8, 0), time(20, 0)),
    # Health / medical
    "Veterinarian":                       (time( 8, 0), time(17, 0)),
    "Family-General Practice Physicians": (time( 8, 0), time(17, 0)),
    "Hospital or Health Care Facility":   (time( 0, 0), time(23, 59)),
    # Government / community
    "Government Office":                  (time( 8, 0), time(16, 0)),
    "Government or Community Facility":   (time( 8, 0), time(16, 0)),
    "Civic-Community Center":             (time( 8, 0), time(17, 0)),
    "Social Service":                     (time( 8, 0), time(17, 0)),
    "Organizations and Societies":        (time( 8, 0), time(17, 0)),
    "Fulfillment and Distribution Center":(time( 8, 0), time(17, 0)),
    "Warehouse":                          (time( 8, 0), time(17, 0)),
    "Facilities":                         (time( 8, 0), time(17, 0)),
    # Education
    "Primary School":                     (time( 7, 0), time(14, 0)),
    "Secondary School":                   (time( 7, 0), time(15, 0)),
    "Education Facility":                 (time( 8, 0), time(16, 0)),
    "Collective Community":               (time( 8, 0), time(17, 0)),
    # Recreation / entertainment
    "Tourist Attraction":                 (time( 8, 0), time(20, 0)),
    "Golf Practice Range":                (time( 6, 0), time(20, 0)),
    "Live Entertainment-Music":           (time(18, 0), time(23, 0)),
    "Nightlife-Entertainment":            (time(20, 0), time(23, 0)),
    "Basketball":                         (time( 7, 0), time(22, 0)),
    "Swimming Pool":                      (time( 6, 0), time(21, 0)),
    "Sporting Instruction and Camps":     (time( 7, 0), time(20, 0)),
    "Cinema":                             (time(10, 0), time(23, 0)),
    "Leisure":                            (time( 9, 0), time(22, 0)),
    "Theatre, Music and Culture":         (time(10, 0), time(22, 0)),
    "Park-Recreation Area":               (time( 6, 0), time(21, 0)),
    "Sports Field":                       (time( 7, 0), time(21, 0)),
    "Sports Facility-Venue":              (time( 7, 0), time(22, 0)),
    "Event Spaces":                       (time( 8, 0), time(22, 0)),
    "Aquarium":                           (time( 9, 0), time(18, 0)),
    "Museum":                             (time( 9, 0), time(17, 0)),
    "Casino":                             (time(12, 0), time(23, 0)),
    "Race Track":                         (time( 8, 0), time(20, 0)),
    "Running Track":                      (time( 5, 0), time(21, 0)),
    "Garden":                             (time( 6, 0), time(18, 0)),
    # Religion
    "Temple":                             (time( 6, 0), time(20, 0)),
    "Church":                             (time( 7, 0), time(20, 0)),
    "Religious Place":                    (time( 6, 0), time(20, 0)),
    # Hospitality
    "Guest House":                        (time( 6, 0), time(23, 0)),
    "Hotel or Motel":                     (time( 6, 0), time(23, 0)),
    "Lodging":                            (time( 6, 0), time(23, 0)),
    "Bed and Breakfast":                  (time( 6, 0), time(21, 0)),
    "Hostel":                             (time( 6, 0), time(22, 0)),
    "Clubhouse":                          (time( 8, 0), time(22, 0)),
    "Apartment Rental-Flat Rental":       (time( 8, 0), time(17, 0)),
    # No EDC / no operating hours
    "Public Restroom-Toilets":            None,
    "Police Box":                         None,
    "Police Station":                     None,
    "Parking Lot":                        None,
    "Parking Garage-Parking House":       None,
    "Motorcycle, Moped and Scooter Parking": None,
    "Bus Station":                        None,
    "Taxi Stand":                         None,
    "Public Transit Access":              None,
    "Tollbooth":                          None,
    "Construction":                       None,
    "Manufacturing":                      (time( 7, 0), time(17, 0)),
    "Market":                             (time( 6, 0), time(18, 0)),
    "Adult Entertainment":                (time(20, 0), time(23, 0)),
    "Utilities":                          None,
    "Mining":                             None,
    "Mining, Quarrying and Other Extraction": None,
    "Industrial Zone":                    None,
    "Farming":                            None,
    "Building":                           None,
    "Natural and Geographical":           None,
    "Beach":                              None,
    "River":                              None,
    "COVID-19 Testing Site":              (time( 8, 0), time(17, 0)),
}

# Categories that are realtime-signal POIs only — no EDC terminal.
# Auto-derived: any category with None hours + Bank (has hours but no card terminal).
REALTIME_CATEGORY_SET: frozenset[str] = frozenset(
    {k for k, v in CATEGORY_DEFAULT_HOURS.items() if v is None} | {"Bank"}
)

# ──────────────────────────────────────────────────────────────────────────────
# TIMEZONE
# ──────────────────────────────────────────────────────────────────────────────

WIB = timezone(timedelta(hours=7))   # Waktu Indonesia Barat (UTC+7)

# ── card image colours (GitHub dark palette) ──────────────────────────────────
_C_BG      = "#0d1117"
_C_PANEL   = "#161b22"
_C_BORDER  = "#30363d"
_C_NAME    = "#e6edf3"
_C_LABEL   = "#8b949e"
_C_VALUE   = "#c9d1d9"
_C_ACTIVE  = "#3fb950"
_C_INACTIVE= "#d29922"
_C_SUSPEND = "#f85149"
_C_REASON  = "#58a6ff"
_C_DIVIDER = "#21262d"

_CARD_W    = 620
_PAD       = 28
_LH        = 24   # line height px

# ──────────────────────────────────────────────────────────────────────────────
# REPORT WINDOW CONSTANTS
# ──────────────────────────────────────────────────────────────────────────────

WINDOW_DAYS          = 30
REALTIME_ACTIVE_DAYS = 90

# ──────────────────────────────────────────────────────────────────────────────
# INPUT PATH CONSTANTS
# ──────────────────────────────────────────────────────────────────────────────

BATCH_UNIFIED_CSV = INPUT_DIR / "list_edc.csv"
REALTIME_CSV      = INPUT_DIR / "list_realtime.csv"
